export const CREDITS = [
  { role: 'Playable character (Odysseus)', asset: 'Fire_Warrior', author: 'Dreamir' },
  { role: 'Playable character (pending, $15)', asset: 'Platformer Character Pack', author: 'Merakintsugi' },
  { role: 'Character backup', asset: 'Fantasy Knight', author: 'aamatniekss' },
  { role: 'Main enemies', asset: 'Hero and Opponents Animation', author: 'Szadi art.' },
  { role: 'Extra enemy', asset: 'FREE Knight 2D Pixel Art', author: 'Mattz Art' },
  { role: 'Mid-boss (shapeshifting)', asset: '2D Pixel Art Horror Enemy Pack', author: 'AshDeal' },
  { role: 'Prologue final boss', asset: 'Boss: Mecha-Stone Golem [FREE]', author: 'Kronovi-' },
  { role: 'Level tileset', asset: 'Legacy Fantasy - Debug Map', author: 'Anokolisa' },
  { role: 'Megalópolis background', asset: 'Synth Cities Environment', author: 'ansimuz' },
  { role: 'VFX (general)', asset: 'Super Pixel Effects Gigapack', author: 'unTied Games' },
  { role: 'UI / HUD', asset: 'Basic Pixel Health bar and Scroll bar', author: 'BDragon1727' },
  { role: 'VFX (slash / impact)', asset: '750 Effect and FX Pixel All', author: 'BDragon1727' },
  { role: 'VFX (projectiles)', asset: 'Free Effect and Bullet 16x16', author: 'BDragon1727' },
  { role: 'Title / level font', asset: 'Pixeloid', author: 'GGBotNet' },
  { role: 'Dialogue font', asset: 'Font+ [Hero Speak]', author: 'SciGho' },
];
