export const CREDITS = [
  { role: 'Playable character (Odysseus)', asset: 'Fire_Warrior', author: 'Dreamir', url: 'https://dreamir.itch.io/fire-warrior' },
  { role: 'Character backup', asset: 'Fantasy Knight', author: 'aamatniekss', url: 'https://aamatniekss.itch.io/fantasy-knight-free-pixelart-animated-character' },
  { role: 'Main enemies', asset: 'Hero and Opponents Animation', author: 'Szadi art.', url: 'https://szadiart.itch.io/hero-and-opponents-animation' },
  { role: 'Extra enemy', asset: 'FREE Knight 2D Pixel Art', author: 'Mattz Art', url: 'https://xzany.itch.io/free-knight-2d-pixel-art' },
  { role: 'Mid-boss (shapeshifting)', asset: '2D Pixel Art Horror Enemy Pack', author: 'AshDeal', url: 'https://ashdeal.itch.io/horror-enemy-pack' },
  { role: 'Prologue final boss', asset: 'Boss: Mecha-Stone Golem [FREE]', author: 'Kronovi-', url: 'https://darkpixel-kronovi.itch.io/mecha-golem-free' },
  { role: 'Level tileset', asset: 'Legacy Fantasy - Debug Map', author: 'Anokolisa', url: 'https://anokolisa.itch.io/sidescroller-pixelart-sprites-asset-pack-forest-16x16' },
  { role: 'Megalópolis background', asset: 'Synth Cities Environment', author: 'ansimuz', url: 'https://ansimuz.itch.io/cyberpunk-street-environment' },
  { role: 'VFX (general)', asset: 'Super Pixel Effects Gigapack', author: 'unTied Games', url: 'https://untiedgames.itch.io/super-pixel-effects-gigapack' },
  { role: 'UI / HUD', asset: 'Basic Pixel Health bar and Scroll bar', author: 'BDragon1727', url: 'https://bdragon1727.itch.io/basic-pixel-health-bar-and-scroll-bar' },
  { role: 'VFX (slash / impact)', asset: '750 Effect and FX Pixel All', author: 'BDragon1727', url: 'https://bdragon1727.itch.io/750-effect-and-fx-pixel-all' },
  { role: 'VFX (projectiles)', asset: 'Free Effect and Bullet 16x16', author: 'BDragon1727', url: 'https://bdragon1727.itch.io/free-effect-and-bullet-16x16' },
  { role: 'Title / level font', asset: 'Pixeloid', author: 'GGBotNet', url: 'https://ggbot.itch.io/pixeloid-font' },
  { role: 'Dialogue font', asset: 'Font+ [Hero Speak]', author: 'SciGho', url: 'https://ninjikin.itch.io/font-hero-speak' },
];
